### ISSUE TITLE
4.6的sql能用了么？

### ISSUE THREAD

**Issue by acheng-floyd** [ixrjog/opscloud4#79]
编译了master分支的版本，程序能运行，但是提示数据库缺少 quartz的表，还有其他的sql报错
https://opscloud4-web.oss-eu-west-1.aliyuncs.com/package/4.6.0/opscloud4-github.sql

```
2024-08-25T11:50:31.289+08:00  INFO 26689 --- [opscloud] [           main] org.quartz.impl.StdSchedulerFactory      : Quartz scheduler 'schedulerFactoryBean' initialized from an externally provided properties instance.
2024-08-25T11:50:31.289+08:00  INFO 26689 --- [opscloud] [           main] org.quartz.impl.StdSchedulerFactory      : Quartz scheduler version: 2.3.2
2024-08-25T11:50:31.291+08:00  INFO 26689 --- [opscloud] [           main] org.quartz.core.QuartzScheduler          : JobFactory set to: org.springframework.scheduling.quartz.AdaptableJobFactory@7fe646a
2024-08-25T11:50:33.368+08:00 ERROR 26689 --- [opscloud] [           main] o.s.s.quartz.LocalDataSourceJobStore     : ClusterManager: Error managing cluster: Failure obtaining db row lock: Table 'opscloud4.qrtz_LOCKS' doesn't exist

org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: Table 'opscloud4.qrtz_LOCKS' doesn't exist`
```
```
2024-08-25T11:50:33.398+08:00 ERROR 26689 --- [opscloud] [_MisfireHandler] o.s.s.quartz.LocalDataSourceJobStore     : MisfireHandler: Error handling misfires: Database error recovering from misfires.

org.quartz.JobPersistenceException: Database error recovering from misfires.
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3274)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:4012)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:4033)
Caused by: java.sql.SQLSyntaxErrorException: Table 'opscloud4.qrtz_TRIGGERS' doesn't exist
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:912)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:968)
        at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:213)
        at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.countMisfiredTriggersInState(StdJDBCDelegate.java:393)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3253)
        ... 2 common frames omitted

2024-08-25T11:50:35.121+08:00  WARN 26689 --- [opscloud] [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'instanceFacadeImpl' defined in URL [jar:nested:/data/opscloud4-prod/opscloud-manage-prod.jar/!BOOT-INF/classes/!/com/baiyi/opscloud/facade/sys/impl/InstanceFacadeImpl.class]: 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'version' in 'field list'
### The error may exist in com/baiyi/opscloud/mapper/InstanceMapper.java (best guess)
### The error may involve com.baiyi.opscloud.mapper.InstanceMapper.selectOneByExample-Inline
### The error occurred while setting parameters
### SQL: SELECT  id,name,hostname,host_ip,status,is_active,version,comment,create_time,update_time,license  FROM instance  WHERE (       (  host_ip = ? ) )
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'version' in 'field list'
; bad SQL grammar []
2024-08-25T11:50:35.124+08:00  INFO 26689 --- [opscloud] [           main] org.quartz.core.QuartzScheduler          : Scheduler schedulerFactoryBean_$_demo-opscloud41724557830744 shutting down.
2024-08-25T11:50:35.124+08:00  INFO 26689 --- [opscloud] [           main] org.quartz.core.QuartzScheduler          : Scheduler schedulerFactoryBean_$_demo-opscloud41724557830744 paused.
2024-08-25T11:50:35.125+08:00  INFO 26689 --- [opscloud] [           main] org.quartz.core.QuartzScheduler          : Scheduler schedulerFactoryBean_$_demo-opscloud41724557830744 shutdown complete.
2024-08-25T11:50:35.145+08:00  INFO 26689 --- [opscloud] [           main] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} closing ...
2024-08-25T11:50:35.150+08:00  INFO 26689 --- [opscloud] [           main] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} closed
2024-08-25T11:50:35.153+08:00  INFO 26689 --- [opscloud] [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2024-08-25T11:50:35.209+08:00 ERROR 26689 --- [opscloud] [           main] o.s.boot.SpringApplication               : Application run failed
```

**Comment by acheng-floyd** [comment]
```
2024-08-25T11:50:33.398+08:00 ERROR 26689 --- [opscloud] [_MisfireHandler] o.s.s.quartz.LocalDataSourceJobStore     : MisfireHandler: Error handling misfires: Database error recovering from misfires.

org.quartz.JobPersistenceException: Database error recovering from misfires.
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3274)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:4012)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:4033)
Caused by: java.sql.SQLSyntaxErrorException: Table 'opscloud4.qrtz_TRIGGERS' doesn't exist
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:912)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:968)
        at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:213)
        at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.countMisfiredTriggersInState(StdJDBCDelegate.java:393)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3253)
        ... 2 common frames omitted

2024-08-25T11:50:35.121+08:00  WARN 26689 --- [opscloud] [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'instanceFacadeImpl' defined in URL [jar:nested:/data/opscloud4-prod/opscloud-manage-prod.jar/!BOOT-INF/classes/!/com/baiyi/opscloud/facade/sys/impl/InstanceFacadeImpl.class]: 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'version' in 'field list'
### The error may exist in com/baiyi/opscloud/mapper/InstanceMapper.java (best guess)
### The error may involve com.baiyi.opscloud.mapper.InstanceMapper.selectOneByExample-Inline
### The error occurred while setting parameters
### SQL: SELECT  id,name,hostname,host_ip,status,is_active,version,comment,create_time,update_time,license  FROM instance  WHERE (       (  host_ip = ? ) )
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'version' in 'field list'
; bad SQL grammar []
2024-08-25T11:50:35.124+08:00  INFO 26689 --- [opscloud] [           main] org.quartz.core.QuartzScheduler          : Scheduler schedulerFactoryBean_$_demo-opscloud41724557830744 shutting down.
2024-08-25T11:50:35.124+08:00  INFO 26689 --- [opscloud] [           main] org.quartz.core.QuartzScheduler          : Scheduler schedulerFactoryBean_$_demo-opscloud41724557830744 paused.
2024-08-25T11:50:35.125+08:00  INFO 26689 --- [opscloud] [           main] org.quartz.core.QuartzScheduler          : Scheduler schedulerFactoryBean_$_demo-opscloud41724557830744 shutdown complete.
2024-08-25T11:50:35.145+08:00  INFO 26689 --- [opscloud] [           main] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} closing ...
2024-08-25T11:50:35.150+08:00  INFO 26689 --- [opscloud] [           main] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} closed
2024-08-25T11:50:35.153+08:00  INFO 26689 --- [opscloud] [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2024-08-25T11:50:35.209+08:00 ERROR 26689 --- [opscloud] [           main] o.s.boot.SpringApplication               : Application run failed
```

**Comment by acheng-floyd** [comment]
用4.6 pre编译就可以了
